package org.csgames.spaceship.sdk;

public enum EventType {
  WATER_SENT,
  DOOR_OPEN,
  DOOR_CLOSED,
  MOVED_TO,
  FISH_FETCHED,
  WATER_FETCHED,
  FISH_CAUGHT,
  WATER_REFILLED,
  AIR_VENT_OPEN,
  AIR_VENT_CLOSED,
  AIR_CONDITIONING_STARTED,
  AIR_CONDITIONING_STOPPED,
  HEATING_STARTED,
  HEATING_STOPPED,
  TEAM_STATUS_REPORTED,
  MEASURED_DATA_REPORTED,
  FISH_SENT
}
