package org.csgames.spaceship.sdk;

public enum EventType {
  WATER_SENT,
  DOOR_OPEN,
  DOOR_CLOSED,
  MOVED_TO,
  FISH_FETCHED,
  WATER_FETCHED,
  FISH_CAUGHT,
  WATER_REFILLED,
  AIR_CONDITIONING_OPEN,
  AIR_CONDITIONING_CLOSED,
  TEAM_STATUS_REPORTED,
  VENT_OPEN,
  VENT_CLOSED,
  ROOM_TEMPERATURE_READ,
  MEAN_HABITABLE_TEMPERATURE_READ,
  FISH_SENT
}
